### ISSUE TITLE
Enter/Exit message prefix

### ISSUE THREAD

**Issue by MithrandirCraft** [ShaneBeee/GriefPreventionFlags#103]
### Description
Please add a configuration for adding a prefix for EnterMessage & ExitMessage flags.
Some players have been using these flags to display misleading messages that confuse players, pretty much anything you could imagine, since there's no prefix that can let players understand the origin of the enter and leave messages. Like "We have detected you are using hacks" (You see anything these days).

**Comment by ShaneBeee** [comment]
1) There already is an option for a prefix (its in the messages file)
2) If your players are abusing the system/flags, maybe you should remove permissions from them.
This plugin was originally intended for admins to flag different claims, not really meant for players.

**Comment by MithrandirCraft** [comment]
Oh ok? I didn't notice that. All good then.

I actually set it up mainly for players to have some more control over their claims, the fact that it could actually substitute worldguard was just a plus.

keep that in mind, because I'm sure I'm not the only one. It actually makes quite a lot of sense if you think about the fact that GP in itself is player-oriented.
