### ISSUE TITLE
How to fly in claims?

### ISSUE THREAD

**Issue by redcreeper14385** [ShaneBeee/GriefPreventionFlags#109]
Hello,
I ran `/setdefaultclaimflag ownermemberfly` to allow people to fly within their claims, and when I go into a claim I cannot fly by double-tapping space. Am I missing something? 

_(I am running Spigot 1.16.1)_

**Comment by ShaneBeee** [comment]
Any console errors or anything?

**Comment by redcreeper14385** [comment]
No, not that I can see.

**Comment by ShaneBeee** [comment]
Without any real information, my guess here is you have another plugin overriding, and blocking flight in claims.

**Comment by redcreeper14385** [comment]
Hmm I'll take a look.

**Comment by redcreeper14385** [comment]
Closing since it's not an issue with this plugin, I'll reopen/open a new one if necessary.
