### ISSUE TITLE
Enter/Exit message still spamming when two child claims are directly adjacent

### ISSUE THREAD

**Issue by jabbink** [ShaneBeee/GriefPreventionFlags#111]
### Description
After implementing #108 most message spam of entering and leaving subclaims where the parent has a message attached to it disappears, but the old issue persists when the two subclaims you leave/enter are directly attached to each other (side by side).

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/2461972/88792302-4e2e1380-d19b-11ea-96b3-5cfed2db0cf2.png)

Imagine yellow is a top level claim with Enter/Exit message, green and red are subclaims that don't have any space inbetween them.

Stand in green, and walk to red: the exit message of yellow shows directly followed by the enter message of yellow

### Expected Behavior

After applying #108 I expect no message at all in chat.

### Server Information
* **Server version/platform:**        `git-Paper-125 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)` 
* **GriefPrevention Version:**        `16.14.0` 
* **GriefPreventionFlags Version:**   c9087c133a4e1cca2b67d6dd86c05a550120c0cc

**Comment by ShaneBeee** [comment]
Marking as completed.... cause well, you fixed it 👍 

Thanks btw :)
