### ISSUE TITLE
not compatibel with luckyperms

### ISSUE THREAD

**Issue by donvdp** [ShaneBeee/GriefPreventionFlags#112]
--> Followed, thanks for the template.

### Description
the permission nodes do not work when using server specific permisison nodes via "luckyperms".

### Steps to Reproduce
in luckperms add permission node "gpflags.allflags" to a group called "speler " in the server "survival".
- command looks like: "/lp group speler permission set gpflags.allflags true survival"

### Expected Behavior
the expected result would be to have access to ingame command "/allflags" for all players of the survival server that are ranked as "speler".

### Errors / Screenshots
the error that i get is that the players has insufficient permissions to execute that command.

### Server Information
* **Server version/platform:**        PAPERMC.version 99
* **GriefPrevention Version:**        GriefPrevention-16.14.0.jar
* **GriefPreventionFlags Version:**   GriefPreventionFlags-5.9.1.jar

### Additional Info
i can get the permission to work by setting the permission node to the global group. This command looks like:
- /lp group speler permission set gpflags.allflags true

**Comment by ShaneBeee** [comment]
That is not what that permission is for, that permission gives the user access to set/remove all flags. 
Has nothing to do with the all flags command.

**Comment by ShaneBeee** [comment]
Closing due to no response.

**Comment by donvdp** [comment]
There was no question, so that is why i did not feel the need to reply, You made a statement about the content of the allflags commando, this was in my description an example that doesnt have anything to do with the compatibility issues with luckyperms. due to the failure of a few more flags with your plugin we've switched to another griefprevention plugin.
