### ISSUE TITLE
Enter Command/Message on join

### ISSUE THREAD

**Issue by ShaneBeee** [ShaneBeee/GriefPreventionFlags#13]
Report on Spigot by arboriginal

Found a (very) small issue with enterMessage/command. When a player is connecting to the server, those events are not triggered if he spawns directly in the claim. I saw this by testing the /pweather (not yet tested with the new flag).

**Comment by ShaneBeee** [comment]
Okay this has been fixed, and will be coming out in the next update!

**Comment by arboriginal** [comment]
I confirm it's working with the current source code compiled.
