### ISSUE TITLE
Subclaims and Parent Claims Flag interactions.

### ISSUE THREAD

**Issue by Nick2bad4u** [ShaneBeee/GriefPreventionFlags#131]
### Description
Hello -

I searched for a bit and couldn't find any concrete information on this.

Do sub-claims inherit all parent claim flags?

Is there a way to disable this on a subclaim basis? Or turn it off by default and only make them inherit if you want?

Let me know -

Thanks

**Comment by ShaneBeee** [comment]
> Do sub-claims inherit all parent claim flags?

yes

> Is there a way to disable this on a subclaim basis? Or turn it off by default and only make them inherit if you want?

no, you would need to manually turn it off per sub claim

**Comment by Nick2bad4u** [comment]
> no, you would need to manually turn it off per sub claim

How do you do this? I looked for inherit, etc.

**Comment by ShaneBeee** [comment]
you just go into the subclass and run the command to remove the flag, I think its `/unsetclaimflag <flag>`

**Comment by Nick2bad4u** [comment]
> you just go into the subclass and run the command to remove the flag, I think its `/unsetclaimflag <flag>`

ahh okay. I see. Sorry :)
