### ISSUE TITLE
Allow the ability to globally enable/disable PVP in a world via a command

### ISSUE THREAD

**Issue by Tnology** [ShaneBeee/GriefPreventionFlags#135]
I think it would be great if you were able to globally enable/disable PVP in a world via a command, which would ignore all flags.
For example: /forcepvp world true
And: /forcepvp world_nether false
And: /forcepvp world_the_end reset

**Comment by ShaneBeee** [comment]
just disable PVP rules in the GriefPrevention config.

**Comment by Tnology** [comment]
How does that have anything to do with the commands? Sorry if I sound rude, and I'm not trying to come off that way. I'm just wondering how that has to do with using a command to toggle it globally. Thank you!!

**Comment by ShaneBeee** [comment]
Why would you need commands to enable/disable PvP for a world, when its in GPs config?

**Comment by Tnology** [comment]
> Why would you need commands to enable/disable PvP for a world, when its in GPs config?

Just makes it easier so I don't have to go into FTP and then into my config. ¯\_(ツ)_/¯

**Comment by ShaneBeee** [comment]
The point of GP flags, is to add flags for things that GP does not have control for.

GP has PvP rules for claims. GPFlags has a flag for allowing to bypass GPs rules for PVP in claims.

Personally I don't think it fits with GP/GPFlags to have commands to manage PvP for entire worlds.

**Comment by boehs** [comment]
Agreed, outside of this projects scope
