### ISSUE TITLE
[Feature Request] Player time flag

### ISSUE THREAD

**Issue by ShaneBeee** [ShaneBeee/GriefPreventionFlags#14]
Suggested by arboriginal on Spigot

New idea, same as PlayerWeatherFlag => PlayerTimeFlag (/ptime).

**Comment by ShaneBeee** [comment]
This has been added and will appear in the next update :)

**Comment by arboriginal** [comment]
I've seen it when getting your source code and compile it.
Tried on my local server, seems to works fine. :)
