### ISSUE TITLE
[Suggestion] noFireSpread Flag

### ISSUE THREAD

**Issue by SteeltonMC** [ShaneBeee/GriefPreventionFlags#19]
What is the possibility to get a fire-spread flag for this plugin? :)

My goal is to replace World Guard as it seems to have poor performance lately.

**Comment by ShaneBeee** [comment]
As discussed on Discord:
You can disable fire spread in the GP config.
The OP is wanting fire spread ON in his world and OFF in flagged claims.
I can totally add this flag.

**Comment by SteeltonMC** [comment]
Thank you very much friend.

**Comment by ShaneBeee** [comment]
Okay, so I wrote the flag and then I realized, even with fire spread protection turned off in the GP config, fire will NOT spread in claims.

I made a suggestion to RoboMWM in his repo for GP to add a configurable option for fire spread in claims. 
We shall wait to hear back on that matter.

**Comment by ShaneBeee** [comment]
**UPDATE:**
RoboMWM responded, saying it could be added, and someone could do a PR for it.
I did a PR, he approved it. SO I guess now we just wait for a release where he merges it into. 
I built the flag, and it works... now we just wait!!

**Comment by ShaneBeee** [comment]
Okay, this is in the new update I just released, but its basically useless until GriefPrevention adds the PR and releases it.
