### ISSUE TITLE
2 in 1 McMMO + Spleef (semi-related)

### ISSUE THREAD

**Issue by CeIebrimbor** [ShaneBeee/GriefPreventionFlags#22]
Kinda two reports in one, but both small items I believe. I came across them both as a result of setting up a Spleef arena.

1. Players gain McMMO EXP in NoMcMMOSkills flagged claims. This is problematic for my new Spleef arena since it regens snow all day (endless grinding).
2. Items drop in Spleef arena. Snowballs drop like crazy all over my arena. Pretty sure the flag intents to prevent block drops.

GPFlags: 4.15.0
GP: 16.11.5
Server: Paper 1.13.2 (#474)

**Comment by ShaneBeee** [comment]
1) I will take a look into this, thank you!
2) I actually found that out the other day when I was testing how the Spleef works. It's been fixed already and will appear in the next update :)

**Comment by ShaneBeee** [comment]
Okay so apparently theres nothing in there regarding McMMo experience. 
I added a test of it, give this a try. If it works, Ill create another flag for it, something like NoMcMMoXP
[Download](
https://github.com/ShaneBeee/GriefPreventionFlags/releases/tag/4.15.1-Beta)

**Comment by ShaneBeee** [comment]
Dang.   Ok when I get home i’ll try again.  I thought I grabbed the right event from mcmmo but apparently not

**Comment by CeIebrimbor** [comment]
Did you add a new flag for McMMO? I didn't see it. I set the NoSkills flag and it was the same as before.

**Comment by ShaneBeee** [comment]
No.   I just added the event to the skills one for testing purposes before I went added a whole new flag.   I’ll put mcmmo on my test server and see if I can figure it out

**Comment by ShaneBeee** [comment]
Okay, [THIS ONE](https://github.com/ShaneBeee/GriefPreventionFlags/releases/tag/4.15.2-Beta) Should do the trick 🤞  I think its the right event

**Comment by CeIebrimbor** [comment]
No jar ???

**Comment by CeIebrimbor** [comment]
Works!

**Comment by ShaneBeee** [comment]
> Works!

Awesome. I'll work on creating a flag for it, and have it ready for the next update!
Thanks for testing!

**Comment by ShaneBeee** [comment]
Okay, this all ready to go in the newest release :)
