### ISSUE TITLE
[Requests][Bug] (minor) Flight & Mobs

### ISSUE THREAD

**Issue by OpalMoonstride** [ShaneBeee/GriefPreventionFlags#24]
I apologize for my wall-o-text.
Flight (bugs?): 
* The flight flag for claims does not disable when TPing from one claim with flight, to another claim, which has flight set, even if the player is not a member of the other claim. 
* Players who are trusted in a claim keep flight, even after being untrusted
* Players' flight is not set to true on join. They have to exit the claim, and re-enter, to enable flight.
* Ownerfly conflicts with ownermemberfly, causing it to enable and disable flight repeatedly.  This can just be confusing since I allow players to set either flag within claimed regions.

Mobs (Bugs?):
* I'm not sure if this is GPflags, or GP, but mobs will appear to spawn in region with the nomonsterspawns flag, and then disappear when walking up to them. This is particularly strange when you're shot once, and then a skeleton disappears, or when a spider appears, and leaves webs behind. I'm not sure if you can fix that, or not. As of right now I'm using GP exclusively for protection, no WorldGuard. 

Requests:
* Would it be possible for you to change the way exiting a claim works, with flight? Something like
`` playername.setFallDistance(-100000);`` instead of teleporting them to the ground when exiting the claim. Teleporting to the ground seems to have adverse affects, such as death, and it's actually really jarring for players. From what I understand, there's a weird velocity issue with TPing, and it can keep the velocity, when exiting, and then the player dies when they touch down. 
* Any way I could possibly whitelist custom mobs for regions with nomonsterspawns flag?

**Comment by ShaneBeee** [comment]
Hey, If you could do me a favour, could you please split this up into separate issues for each topic, this way I can tackle of them individually?

Thank you!

**Comment by OpalMoonstride** [comment]
Sure, sorry!
