### ISSUE TITLE
Flight flag does not disable when switching claims

### ISSUE THREAD

**Issue by OpalMoonstride** [ShaneBeee/GriefPreventionFlags#25]
The flight flag for claims does not disable when TPing from one claim with flight, to another claim, which has flight set, even if the player is not a member of the other claim.

Paper SPigot 1.13.2
GPFlags 4.16.1
GP 16.11.5

**Comment by ShaneBeee** [comment]
Okay I totally know the issue here. I'm sure I can fix this.

**Comment by ShaneBeee** [comment]
This has also been fixed
