### ISSUE TITLE
Flight not set to true on join

### ISSUE THREAD

**Issue by OpalMoonstride** [ShaneBeee/GriefPreventionFlags#27]
Players' flight is not set to true on join. They have to exit the claim, and re-enter, to enable flight.

Paper SPigot 1.13.2
GPFlags 4.16.1
GP 16.11.5

**Comment by ShaneBeee** [comment]
This one baffles me. I thought someone reported it before and I fixed it.
Both OwnerFly and OwnerMemberFly have join events, so it SHOULD give them fly. I will have to test this out a bit more.

**Comment by OpalMoonstride** [comment]
So, I'm not sure if it's the same issue, or not, but I have a flight plugin I wrote for Towny, and I had the player join event working, and then spigot released a big update, and it was broken, again. I wound up doing: 
```
Bukkit.getScheduler().runTaskLater(BlockStackTownyFlight.self, () -> {
   <turn on flight stuff>
}, 40);
```
20 ticks didn't work, but 40 did. I'm not sure if that might be helpful for flags?

**Comment by OpalMoonstride** [comment]
Weird. Okay! I will do more testing. Maybe I screwed something up. Thank you!

**Comment by ShaneBeee** [comment]
I test this a few times, unfortunately I can not reproduce this issue.
Im going to close it for now, but If I happen to come across it at some point, Ill make sure to make note here.

I installed EssentialsX on my test server and it didn't impact it at all.
