### ISSUE TITLE
Ownerfly conflicts with ownermemberfly

### ISSUE THREAD

**Issue by OpalMoonstride** [ShaneBeee/GriefPreventionFlags#28]
Ownerfly conflicts with ownermemberfly, causing it to enable and disable flight repeatedly. This can just be confusing since I allow players to set either flag within claimed regions.

Paper SPigot 1.13.2
GPFlags 4.16.1
GP 16.11.5

**Comment by ShaneBeee** [comment]
These two flags are not meant to work with each other. 
It is meant to use 1 or the other, since OwnerFly is just owner and OwnerMemberFly is owner and members.

I can take a look into stopping both flags from being defined in one region.

**Comment by ShaneBeee** [comment]
This has been fixed as well.
Players will not be able to set both flags in one claim.

Players whom currently have both flags in one claim will have to remove one or the other or they will continue to have issues.
