### ISSUE TITLE
NoEnter Error

### ISSUE THREAD

**Issue by coco0325** [ShaneBeee/GriefPreventionFlags#3]
04.09 18:24:36 [Server] WARN java.lang.NullPointerException
04.09 18:24:36 [Server] WARN at me.ryanhamshire.GPFlags.FlagDef_NoEnter.allowMovement(FlagDef_NoEnter.java:27)
04.09 18:24:36 [Server] WARN at me.ryanhamshire.GPFlags.PlayerMovementFlagDefinition.processPlayer(PlayerMovementFlagDefinition.java:33)
04.09 18:24:36 [Server] WARN at me.ryanhamshire.GPFlags.TimedPlayerFlagDefinition.run(TimedPlayerFlagDefinition.java:63)
04.09 18:24:36 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
04.09 18:24:36 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
04.09 18:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
04.09 18:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
04.09 18:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
04.09 18:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
04.09 18:24:36 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by ShaneBeee** [comment]
Im going to need more info to be able to replicate this issue.
Which version of a server are you using and which server software?
Also which version of GP flags and which version of GP are you using?

**Comment by ShaneBeee** [comment]
22 days, no reply, closing this for now!
