### ISSUE TITLE
Request: setfalldistance(-100000) instead of tp to ground?

### ISSUE THREAD

**Issue by OpalMoonstride** [ShaneBeee/GriefPreventionFlags#30]
Would it be possible for you to change the way exiting a claim works, with flight? Something like
playername.setFallDistance(-100000); instead of teleporting them to the ground when exiting the claim. Teleporting to the ground seems to have adverse affects, such as death, and it's actually really jarring for players. From what I understand, there's a weird velocity issue with TPing, and it can keep the velocity, when exiting, and then the player dies when they touch down.

Paper SPigot 1.13.2
GPFlags 4.16.1
GP 16.11.5

**Comment by ShaneBeee** [comment]
Ill definitely take a look at this.

I personally always hated the way this flag pushed you to the ground, and always forced you to face a certain direction (i think north) it just seemed so odd. 
As for the damage from this, I have never experienced that, so Im not sure why that is happening.

**Comment by ShaneBeee** [comment]
I've now changed this, so when a player loses their flight, they will now drop naturally but not take fall damage.
