### ISSUE TITLE
Request: Whitelist mobs (such as mythic mobs) within nomonsterspawns flagged claim?

### ISSUE THREAD

**Issue by OpalMoonstride** [ShaneBeee/GriefPreventionFlags#31]
Any way I could possibly whitelist custom mobs for regions with nomonsterspawns flag?

Paper SPigot 1.13.2
GPFlags 4.16.1
GP 16.11.5

**Comment by ShaneBeee** [comment]
I could totally add a new flag to allow you to deny vanilla mobs, 
but as for custom MM mobs, that Im not entirely sure how I could tackle.

Ill set this an enhancement and see what I can make happen.

**Comment by ShaneBeee** [comment]
Thinking about this more and more, I don't think this is something well suited for this plugin. MythicMobs is quite the plugin, and trying to deny vanilla mobs and allow MythicMobs will get overly convoluted. 

I recommend for something like this, another plugin/addon for GP to be created, I don't feel comfortable adding this to GP Flags
