### ISSUE TITLE
Region owner flag bypass

### ISSUE THREAD

**Issue by CircusCow** [ShaneBeee/GriefPreventionFlags#34]
I would love it if it were possible to allow the owner of the the region to bypass the flag that was created. For example, I am blocking the command /warp create so that other players can't create public warps in another players regions, but then it also removes the ability for the owner to create a warp, which I want them to be able to do.

**Comment by ShaneBeee** [comment]
You can do this right in GriefPrevention.
Theres a list of commands you can blacklist in a region, that only the owner can use,
you do not need GP Flags for this
![](https://i.imgur.com/wnjO2mJ.png)
