### ISSUE TITLE
Suggestion to ignore player name case in NoEnterPlayer flag

### ISSUE THREAD

**Issue by ArtNRG** [ShaneBeee/GriefPreventionFlags#35]
https://github.com/ShaneBeee/GriefPreventionFlags/blob/cdb69d3c18492e32cb6bd2019a363e2d69fb785e/src/me/ryanhamshire/GPFlags/FlagDef_NoEnterPlayer.java#L19

Please add the ignoring string case here.

**Comment by ShaneBeee** [comment]
This has been fixed and will appear in the next update :)
