### ISSUE TITLE
OwnerFly and OwnerMemberFly allow flight outside of a claim

### ISSUE THREAD

**Issue by SkuadMC** [ShaneBeee/GriefPreventionFlags#36]
As the title says, players can just fly in and out of their claim as long as they stay in the same world. They can land on the ground and fly again as well. If they change worlds the flight goes away but otherwise they can just keep flying. 

They do not have any sort of permission conflicts as far as I can tell.
![2019-03-11_08 04 28](https://user-images.githubusercontent.com/46537053/54125931-58981380-43d4-11e9-97d4-020d11a02220.png)

**Comment by ShaneBeee** [comment]
I'll take a look into this again. I feel like I have tested this 100+ times and it worked fine, but Ill have to do more testing.

Which version of GP Flags and Spigot are you using?

**Comment by ShaneBeee** [comment]
I tried to replicate this and had no luck.

Keep in mind, that when you are OP'd you will not lose flight when leaving a claim.
Here is a video, in the first part I am OP'd, when i leave the claim, I can still fly.
If I de-op myself, when I leave the claim I fall to the ground.
[![Alt text](https://img.youtube.com/vi/VPj_l_ao-dc/0.jpg)](https://youtu.be/VPj_l_ao-dc)

**Comment by SkuadMC** [comment]
None of my players (or the account that took the screenshot) are OP'd. We are using the latest version of GP flags. And our spigot version was built using BuildTools roughly 4 days ago (so whatever the latest version was then, can't exactly check at this moment).

**Comment by ShaneBeee** [comment]
Oh the dreaded words every developer hates, "latest"
"Latest tells me nothing" 
For Spigot, are you running the latest 1.12.2, 1.13.2, 1.9.4? This is why "latest" doesn't work.

Im really not sure what else to tell you.
As you can see in the video I posted, I can't seem to replicate the issue.
I love fixing things, but if I can't replicate it, I don't know how to fix it.
Im not saying its not broken, Im saying I cant find the issue.

**Comment by SkuadMC** [comment]
I meant latest 1.13.2. Which is what BuildTools would create. Sorry.

I found the issue, it was a permission. Default players had gpflags.bypass.fly for some reason. Probably sleep deprivation while I was setting up permissions. 

Really sorry for wasting your time.

**Comment by ShaneBeee** [comment]
> I found the issue, it was a permission. Default players had gpflags.bypass.fly for some reason. Probably sleep deprivation while I was setting up permissions.
> 
> Really sorry for wasting your time.

Oopsies.... happens to the best of us
