### ISSUE TITLE
[Enter/Exit] world/server flag not working

### ISSUE THREAD

**Issue by Crack3dC0d3** [ShaneBeee/GriefPreventionFlags#37]
I set a server flag with the same enter message but its not working, However it works when i set the flag to a single claim just not public

**Comment by ShaneBeee** [comment]
Set server flag, is for a flag over the entire server, not claims.
That being said, the "server" wouldn't have an enter/exit message.

I think what you are looking for is
```
SetDefaultClaimFlag
description: Sets a flag on all GriefPrevention land claims.
usage: /SetDefaultClaimFlag <flag> <optional parameters>
aliases: [setdefaultflag, placedefaultflag, putdefaultflag, defaultclaimflag, placedefaultclaimflag, putdefaultclaimflag]
permission: gpflags.defaultflags
```
