### ISSUE TITLE
[Suggestion] Chorus Fruit

### ISSUE THREAD

**Issue by Max0fficial** [ShaneBeee/GriefPreventionFlags#39]
Hi ! there would be a chance to add the possibility of teleportation with the chorus fruit without giving the player the permission  /accestrust

Best regards, Max 😄

**Comment by ShaneBeee** [comment]
This is something that is handled by GriefPrevention itself, and when something is blocked by GP its kinda hard to unblock it. 

In my opinion such a flag is not needed, when you can already give a player `/accesstrust`, if you don't want them to use switches/levers then I don't think chorus fruit should be used.

And to add, I think this flag serves a very small purpose, I can't just add flags for every tiny little thing in the game or this plugin will become way to overloaded with flags.
