### ISSUE TITLE
Playertime and Playerwather flags not compatible EssentialsX

### ISSUE THREAD

**Issue by andris155** [ShaneBeee/GriefPreventionFlags#41]
### Description

Playertime and Playerwather flag not compatible EssentialsX, because reset all locations if set time or weather /ptime or /pweather commands.

### Steps to Reproduce

1. Set Playertime and Playerwather flag.
2. Use EssentialsX /ptime or /pweather command to set set time or weather.
3. Adjusted ptime or pweather reseted all locations.

### Expected Behavior

Adjusted ptime or pweather not reseted all locations.

### Server Information
* **Server version/platform:**        
```
20.04 18:53:51 [Server] INFO This server is running Paper version git-Paper-621 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
20.04 18:53:51 [Server] INFO Previous version: git-Paper-610 (MC: 1.13.2)
```
* **GriefPrevention Version:**        
`GriefPrevention version 16.11.6`
* **GriefPreventionFlags Version:**   
`GriefPreventionFlags version 5.1.2`

### Additional Info

```
20.04 18:55:05 [Server] INFO EssentialsX version: 2.16.1.80
20.04 18:55:05 [Server] INFO LuckPerms version: 4.4.0
20.04 18:55:05 [Server] INFO Vault version: 1.7.1-b${env.TRAVIS_BUILD_NUMBER}
20.04 18:55:05 [Server] INFO EssentialsXGeoIP version: 2.16.1.80
20.04 18:55:05 [Server] INFO EssentialsXChat version: 2.16.1.80
20.04 18:55:05 [Server] INFO EssentialsXSpawn version: 2.16.1.80
```

**Comment by ShaneBeee** [comment]
Ah yes, I see the issue here.

Thank you for reporting, I will start working on a fix for this.

**Comment by andris155** [comment]
Thanks!

**Comment by ShaneBeee** [comment]
> Thanks!

You're very welcome :)
