### ISSUE TITLE
Support /setflag (user) (flag)

### ISSUE THREAD

**Issue by BiGUNMAN** [ShaneBeee/GriefPreventionFlags#42]
### Description
It would be really useful to be able to set flags for users through the console as this allows for extensive customization with external plugins.

Example Command: /setflag (user) (flag) (flag-options)
Or create a separate command that achieves the same goal.

The claim the target player is standing in is the claim that will have the flag applied to.

**Comment by ShaneBeee** [comment]
I like this idea, I think I could make this possible
