### ISSUE TITLE
[Suggestion] Door locking

### ISSUE THREAD

**Issue by remy99c** [ShaneBeee/GriefPreventionFlags#43]
### Description

**Add a flags for locking:**
Doors, gates and trapdoors.
**if possible different flags for:**
Locking for everyone.
Exception for owner.
exception for trusted.

**Comment by ShaneBeee** [comment]
I don't see the need for this, since GriefPrevention already handles door locking.

**Comment by remy99c** [comment]
Griefprevention handles door locking server wide, i want to be able to set a spawn claim where only trapdoors are locked and another claim where everything is locked while having all other claims have no locked doors.

**Comment by ShaneBeee** [comment]
Added in latest release

**Comment by remy99c** [comment]
Thanks, what are the claimflags called? it does not yet specify on the flags page.

**Comment by ShaneBeee** [comment]
Oops that would be because I forgot to add them.
Its `NoOpenDoors`

**Comment by remy99c** [comment]
Does it have any parameters to only lock trapdoors? such as /claimflag NoOpenDoors trapdoors?

**Comment by ShaneBeee** [comment]
no, its just all 3 together

**Comment by remy99c** [comment]
Would it be possible to add those parameters?

**Comment by ShaneBeee** [comment]
I can see if I can make something like that work
