### ISSUE TITLE
[Suggestion] sub-claim flags

### ISSUE THREAD

**Issue by remy99c** [ShaneBeee/GriefPreventionFlags#44]
### Description

Right now it seems like flags get applied to the parent claim, and are effective even in all sub-claims, is it possible that if you stand in a sub-claim while setting a flag, it gets applied only to the sub-claim and when you stand outside the sub-claim but in the parent claim it gets applied to all?
Kinda like how the /trust command handles it.

scenario: Having a nopvp claim with a sub-claim in it where pvp is allowed (for a pvp arena).

not sure if this is possible or if its too much work.

**Comment by ShaneBeee** [comment]
Im a little confused by this. 
As it stands what you are asking for is already done with the plugin.

If I stand in the main/parent claim and set a flag, it will be applied to all subclaims.
If I stand inside of a subclaim and set a flag, that particular flag is only applied to that subclaim:
![](https://i.imgur.com/kCzlchP.png)

**Comment by remy99c** [comment]
It seems like on that part i had mis-configured my claim, sorry about that!

**Comment by ShaneBeee** [comment]
> It seems like on that part i had mis-configured my claim, sorry about that!

No worries, Im glad you got it figured out 👍
