### ISSUE TITLE
Flag not works

### ISSUE THREAD

**Issue by Victor75007** [ShaneBeee/GriefPreventionFlags#45]
### Description
Hello,

i have one problem. 
I use this plugin on 1.13.2 paper spigot server.
Paper version: git-Paper-566 

My players use 6 flags on their claims.
These flags is default claim-flags. 

- Memberfly
- Ownerfly
-------------New flag, what I gave to the players ----------
- NoMobDamage
- NoMonsterSpawn
- KeepLevel
- KeepInventory

But the last 4 flags not works. 
I don't know, why. 

My flag config:
https://pastebin.com/kuYe6uku

No error in console. 

I don't know how it worked before the last update.
These flags is new on my server. I added to my players as defaultclaimflags, because i create custom mobs with MythicMobs, and these custom mobs killed my players on their claim. 

### Server Information
* **Server version/platform:**        1.13.2 /  git-Paper-566 on BungeeCord
* **GriefPrevention Version:**        16.11.6
* **GriefPreventionFlags Version:**   version: 5.3.2

Sorry my english

Can you help me?

Have a nice day!
Best regards, 
Victor

**Comment by ShaneBeee** [comment]
Im going to need some more details
For these flags:
NoMobDamage
NoMonsterSpawn
KeepLevel
KeepInventory

You said they don't work. For each flag, what is the issue you are having?

**Comment by Victor75007** [comment]
**NoMobDamage** is true.
So I think there's no monster damage.
But there is monster-damage.
**NoMonsterSpawn.**
Monster can spawn in the claim from spawner.
If I or my player hitting these mobs, then the mobs does not disappear.
**KeepLevel and KeepInventory**
I use Angelchest.
But if i, or my players die in claims then their XP level and inventory is lose.

**Comment by ShaneBeee** [comment]
NoMobDamage:
- Ill take a look at this

NoMonsterSpawn:
- This only cancels natural spawns, it purposely ignores spawners since a player would have to manually place a spawner.

KeepLevel and KeepInventory:
- Its a known issue that other plugins will override GPFlags. Theres really nothing I can do about this.
Someone mentioned this in the past, I tried to do a work around, but the priority of the other plugin took precedent and there was nothing I could do about it.

**Comment by Victor75007** [comment]
Oh. I don't know these. 
Thank you very much your help!

**Comment by ShaneBeee** [comment]
For **NoMobDamage**, is it vanilla mobs or MythicMobs that are damaging you?

**Comment by Victor75007** [comment]
Vanilla too.
That's important to my players.
Mythic mobs is very few in the world.

**Comment by ShaneBeee** [comment]
Ok Ill do some testing, and if I can replicate the issue, Ill do my best to fix it!

**Comment by Victor75007** [comment]
Thank you very much!

**Comment by ShaneBeee** [comment]
Ok I did testing and I forgot, the NoMobDamage is protecting named and passive mobs in your claims, not players. 

If you want to prevent monsters damaging players, I recommend using the **NoMonsterSpawns** flag, this will prevent monsters spawning in claims, plus when a monster spawns outside of a claim and tries to walk in, it'll vanish.

**Comment by Victor75007** [comment]
Yes, I use NoMonster flag. 
Allright. Then I turn off the NoMobDamage in claims. 
Thank you very much for checked it!

Have a nice day!
Best regards,
Victor

**Comment by ShaneBeee** [comment]
You're welcome.
I'm glad I was able to help you solve your issue.
