### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by coco0325** [ShaneBeee/GriefPreventionFlags#46]
### Description
When player in a NoEnter claim.

### Errors / Screenshots
https://pastebin.com/m9fgEErs

### Server Information
* **Server version/platform:**        Paper
* **GriefPrevention Version:**        16.11.6
* **GriefPreventionFlags Version:**   5.3.3

**Comment by ShaneBeee** [comment]
Can you please add your `flags.yml` file. I can't seem to replicate this issue, I just want to see how your flag is set up.

**Comment by ShaneBeee** [comment]
Im closing this issue, as I have no received a response in 12 days, and I can not replicate this issue.
