### ISSUE TITLE
[Suggestion] NoEnterPlayer Flag - Allow Claim Owner Bypass

### ISSUE THREAD

**Issue by JGuerndt** [ShaneBeee/GriefPreventionFlags#47]
### Description
Just a thought as I was testing, I decided to ban myself from the claim and it works. While not ultimately an issue, users that decide to test this out, end up creating more work for server support to have to UnSet their NoEnterPlayer flag from the claim.

**Comment by ShaneBeee** [comment]
In my opinion, this is a flag that should not be given to players. This is a flag for server admins to stop players from entering certain admin claims.

**Comment by JGuerndt** [comment]
Understood, it is my only use in the plugin to save on harassment issues amongst players. Thanks for looking at it though.

**Comment by ShaneBeee** [comment]
You're welcome. Ill keep this open and take a look at it, and see if this could be implemented.
