### ISSUE TITLE
[Suggestion] NoEnterPlayer - Change in Flag Handling

### ISSUE THREAD

**Issue by JGuerndt** [ShaneBeee/GriefPreventionFlags#48]
### Description
I'm sure this would not be as easy to setup, since it would change the normal behavior of the flag string, but the ability to add/remove players one at a time to the NoEnterPlayer flag would be nice.
Current method:
/SetClaimFlag NoEnterPlayer Player1
to add Player2
/SetClaimFlag NoEnterPlayer Player1,Player2
to remove Player1
/SetClaimFlag NoEnterPlayer Player2

Suggestion would be to have the ability to
/SetClaimFlag NoEnterPlayer Player1
/SetClaimFlag NoEnterPlayer Player2
and it keep the flag as NoEnterPlayer Player1,Player2
then some form of command to remove just one player and keep all others in the flag.

Again, I know this completely changes how flags work, but just a suggestion.

**Comment by ShaneBeee** [comment]
unfortunately this isn't going to happen. The command is to **set** flags, not change their parameters.
