### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by LogGits** [ShaneBeee/GriefPreventionFlags#49]
We have an area in an ocean and players are using boats to enter the area is there a way to make it so people can walk and tp (to and from) but cant enter from the outside? Also is there a way prevent players from placing boats/minecarts in an area?

**Comment by ShaneBeee** [comment]
1) Not as far as I know. You can prevent players entering with the noEnter flag, but there is no option that would allow players to roam around inside the claim, but not enter via walking/boating in.

2) As far as I know, there is nothing to stop the placement of vehicles

**Comment by LogGits** [comment]
Thank you for the quick reply, do you think we could get these 2 features added?

**Comment by ShaneBeee** [comment]
The first one, definitely not. There would be no way I can think of to distinguish walking/boating into a claim vs teleporting into a claim.

The second one, I can take a look and see if I can figure it out, shouldn't be too hard.
