### ISSUE TITLE
[Suggestion] Allow/deny other player triggering machines

### ISSUE THREAD

**Issue by RenaWevin** [ShaneBeee/GriefPreventionFlags#51]
We couldn't find a flag to set if a player can use buttons, pressure plates, levers, etc.
We are aware of that there is a /accesstrust command that can let specific player to use them.
But we would really love to have a flag to make every player in the sever possible to access all those triggering machines.

**Comment by ShaneBeee** [comment]
This is a grief prevention thing, just use `/accesstrust public`
