### ISSUE TITLE
[SUGGESTION] Flags to make certain containers public (Not Trusted)

### ISSUE THREAD

**Issue by Nioxed** [ShaneBeee/GriefPreventionFlags#53]
### Description
Hello, Sorry if there is already a way to do this.
I'd like to be able to make it so anyone can read lecterns (1.14) in my claims.
Right now you need containertrust for that to function..

Do you think this would be possible / a good idea?

**Comment by Nioxed** [comment]
Maybe instead a flag that allows you to have access to inventories in a read-only way? Only looking, no taking

**Comment by ShaneBeee** [comment]
I totally forgot GP has an issue/suggestion already going for this.

I will put this suggestion on hold and see what GP does with it.

Here is the issue if you wish to follow it
https://github.com/TechFortress/GriefPrevention/issues/537

**Comment by ShaneBeee** [comment]
Just to keep you informed, I'm working on adding this directly into GP
https://github.com/TechFortress/GriefPrevention/pull/579

**Comment by ShaneBeee** [comment]
Update... the PR has been added into GP, Robo hasn't released a build yet, but its been added, so I'm going to close this!
