### ISSUE TITLE
Inventory Duplication on Death

### ISSUE THREAD

**Issue by Xardas88** [ShaneBeee/GriefPreventionFlags#54]
### Description

With keepinventory set true Players on death both keep and drop their inventories, duplicating everythings
### Steps to Reproduce

Set flag keepinventory to true
die and keep and drop all inventory
### Expected Behavior

Keep my inventory and not drop it
### Errors / Screenshots

no error in console
### Server Information
* **Server version/platform:**         Paper version git-Paper-152 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
* **GriefPrevention Version:**         16.11.6
* **GriefPreventionFlags Version:**    5.4.2

### Additional Info

There is a change to spigot keepinventory event
 https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-4-development-builds.369724/page-81#post-3491206

**Comment by ShaneBeee** [comment]
Thanks for letting me know, Ill fix this up shortly.
