### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to GriefPreventionFlags v5.5.0

### ISSUE THREAD

**Issue by Weasel-Beans** [ShaneBeee/GriefPreventionFlags#55]
https://pastebin.com/FfxWugEt

I've been getting this issue since that last update. All I know is that it appears in the console a lot and I have some flags around the spawn to stop mobs.

I'm on Paper 1.14.4, build 153

**Comment by ShaneBeee** [comment]
`Calling Entity#remove on players produces undefined (bad) behavior` <-- oops! Clearly I did something wrong, ill take a look at it today and get a fix out soon.
