### ISSUE TITLE
[Suggestion] Permissions for the new NoMobSpawnsType flag

### ISSUE THREAD

**Issue by SkuadMC** [ShaneBeee/GriefPreventionFlags#56]
Basically, let us restrict what mobs people can deny from spawning using permissions. So like if they had gpflags.nomobspawnstype.skeleton they can prevent skeletons from spawning but nothing else. This could be useful for progression based servers so people can like unlock the ability to deny more mobs in their claim.

**Comment by ShaneBeee** [comment]
Added in latest release 5.5.2
