### ISSUE TITLE
Projectiles Blocked in AllowPvP

### ISSUE THREAD

**Issue by CeIebrimbor** [ShaneBeee/GriefPreventionFlags#59]
### Description

100% of arrows get blocked in combat when in an AllowPvP zone. 

I have a CombatTag plugin that tags players in combat and also forces PvP when tagged, so in that case it bypasses the arrows being blocked by GPFlags. This is seen in the video below.

Video: https://youtu.be/OSe3BamDMPY

### Steps to Reproduce
Be inside AllowPvP claim, shoot with bow.

### Expected Behavior
AllowPvp does not block any combat.

### Errors / Screenshots
No errors
![image](https://user-images.githubusercontent.com/14807889/63230451-aa359d00-c1c1-11e9-871e-d7bf580da39f.png)

### Server Information
* **Server version/platform:** 1.14.4 (Paper 167)
* **GriefPrevention Version:** 16.11.6
* **GriefPreventionFlags Version:** 5.5.3

**Comment by ShaneBeee** [comment]
Apparently I already fixed this a while ago, but never pushed an update, not sure why I did that.
