### ISSUE TITLE
NoRaidStart Flag

### ISSUE THREAD

**Issue by JeffDwyer3339** [ShaneBeee/GriefPreventionFlags#60]
Would it be possible to create a flag to disable the activation of raids within a claim? On a large server players can grief other players farms by just entering their areas with the bad omen affect and trigerring a raid.

**Comment by ShaneBeee** [comment]
A few things here
1) Spigot/Bukkit API does not have anything for raid events yet. Therefor theres no proper way for us to catch when they're happening. 
2) This has been suggested to GP already, so Im kind of waiting to see what GP will do when Spigot finally adds the raid events
https://github.com/TechFortress/GriefPrevention/issues/575
