### ISSUE TITLE
Enabling PvP in the config.yml causes arrows to dupe 

### ISSUE THREAD

**Issue by SkuadMC** [ShaneBeee/GriefPreventionFlags#61]
Basically, enable PvP in the config.yml (I have it enabled in all worlds), get a bow with infinity, and shoot yourself. The arrow will automatically duplicate and be added to your inventory.

No errors in console.

Plugins
![1b6063b9622d88d999acc9ead4e16e91](https://user-images.githubusercontent.com/46537053/63905064-a16e7380-c9d8-11e9-9255-f4bfaf97b77c.png)

Paper version
![0439799cd01230052a5854b91df18f23](https://user-images.githubusercontent.com/46537053/63905081-ae8b6280-c9d8-11e9-98e3-7db7c6e6d5f4.png)

GriefPrevention and GriefPreventionFlags version
![a677458e85a73425b828a14dbdcca801](https://user-images.githubusercontent.com/46537053/63905093-b77c3400-c9d8-11e9-8371-ca5a32150c54.png)
![73d9a6660bfff300838fd739e5990ab4](https://user-images.githubusercontent.com/46537053/63905095-b8ad6100-c9d8-11e9-83a6-5c9e9cff5c91.png)

This could easily be an issue with another plugin, however it did not begin until I enabled PvP in the config.yml file.

**Comment by ShaneBeee** [comment]
this is most likely caused by a fix I did recently. Someone stated that when you shoot an entity/player in a non-PvP area, event was cancelled but you lost the arrow, so I returned the arrow.

I guess the same is happening with an infinity bow, Ill have to do a check for that.
