### ISSUE TITLE
The Panda lost if hit in nomonsterspawn claim

### ISSUE THREAD

**Issue by andris155** [ShaneBeee/GriefPreventionFlags#62]
### Description

The Panda lost if hit in nomonsterspawn claim

### Steps to Reproduce

Go to my claim, and set nomonsterspawn flag
Hit panda
Panda lost

### Expected Behavior

The panda don't lost.

### Errors / Screenshots

https://www.youtube.com/watch?v=-mmSPr42JJU

### Server Information
* **Server version/platform:**        
This server is running Paper version git-Paper-177 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
* **GriefPrevention Version:**        
GriefPrevention version 16.12.0-beta-9125241
* **GriefPreventionFlags Version:**   
GriefPreventionFlags version 5.6.0

**Comment by ShaneBeee** [comment]
The video isn't working.

But let me just get this straight, you dont want monsters in your claim, but you want it so if you hit a panda it will attack you?

**Comment by andris155** [comment]
See again the video.

**Comment by andris155** [comment]
Yes

**Comment by ShaneBeee** [comment]
fixed in latest update

**Comment by andris155** [comment]
Thanks!
