### ISSUE TITLE
/setflagplayer ChangeBiome not working.

### ISSUE THREAD

**Issue by IxWolfie** [ShaneBeee/GriefPreventionFlags#63]
### Description
When using /setflagplayer **name** ChangeBiome **biome**, the biome is not changed. However, using /setflag with the aforementioned variables will change the biome successfully. Both commands state that they have changed the biome.

### Steps to Reproduce
1. Create a claim.
2. Use /setflagplayer **(ign)** ChangeBiome **(biome)**
3. See that the success message displays. Reload the chunks and see that the biome is not changed.
4. Use /setflag **(ign)** ChangeBiome **(biome)**
5. See that the success message displays, and upon reloading the chunks, the biome will successfully update.

### Expected Behavior
Upon using /setflagplayer, the biome should change correctly. Additionally, this is the only flag that does not work with /setflagplayer. The rest apply correctly.

### Errors / Screenshots
None in-game and none in console. I can make a video if necessary documenting the issue.

### Server Information
* **Server version/platform:** Paper 642 (1.13.2)
* **GriefPrevention Version:** 16.11.6
* **GriefPreventionFlags Version:** 5.6.2

### Additional Info
N/A

**Comment by ShaneBeee** [comment]
Its so nice to see a detailed bug report.
Thank you.

Ill take a look into this. I was actually doing a big re-write to that flag anyways (to instantly update the biomes) so good timing on finding this bug.

**Comment by ShaneBeee** [comment]
Just putting some finishing touches on it, but I'll have a fix out for this soon.

[**Check out the progress**](https://youtu.be/qgi9XSg-ZgQ)

**Comment by BiGUNMAN** [comment]
The /setflagplayer command also doesn't do 1.13.2 suggestions, not sure if that's intentional or not.

**Comment by ShaneBeee** [comment]
> The /setflagplayer command also doesn't do 1.13.2 suggestions, not sure if that's intentional or not.

Yeah, that doesn't work in 1.14.x either, it's definitely not intentionally, I was just whipping that command up quickly for someone and I didn't spend time on actually writing the tab completions for it, so I still need to do that.

**Comment by ShaneBeee** [comment]
This issue is now fixed in the latest update [**5.6.3**](https://github.com/ShaneBeee/GriefPreventionFlags/releases/tag/5.6.3)
