### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by FeroxDrood** [ShaneBeee/GriefPreventionFlags#64]
### Description 
When giving the player the permission gpflags.setflag: they then have access to every flag even though they have individual flag permissions set to true and false using gpflags.<flagname>

### Steps to Reproduce
Use paper spigot 1.14.4 build 186, grief prevention flags 5.6.3 and luck perms version 4.4.1

### Expected Behavior
Players should only have access to the flags they have specific perms for

### Errors / Screenshots
N/A 

### Server Information
Server version/platform: Paper Spigot 1.14.4 build 186
GriefPrevention Version: Version 16.12.0
GriefPreventionFlags Version: Version 5.6.3

### Additional Info
N/S

**Comment by ShaneBeee** [comment]
I can't replicate this issue.

OP'd: (I have access to all flags)
![Screen Shot 2019-09-10 at 9 36 58 AM](https://user-images.githubusercontent.com/20008482/64632790-ab1bb200-d3ae-11e9-8959-9413ea34feda.png)

DE-OP'd: (I only have access to the flags with the perms I have - as seen in my PEX perm file)
![Screen Shot 2019-09-10 at 9 37 17 AM](https://user-images.githubusercontent.com/20008482/64632837-c5559000-d3ae-11e9-8317-d3cbfe2f2ea3.png)

When attempting to run the command `/setclaimflag nomonsterspawns` I get the no perm message:
![Screen Shot 2019-09-10 at 9 37 38 AM](https://user-images.githubusercontent.com/20008482/64632864-d1d9e880-d3ae-11e9-9df3-85314d32af02.png)


Im not exactly sure how LuckPerms works, but my guess is you have the perms for the flags set up incorrectly, or maybe you gave the players the permission `gpflags.allflags` ... I'm not entirely sure.

**Comment by ShaneBeee** [comment]
Closing this as there has been no response in 26 days.
