### ISSUE TITLE
Trident vanishes when hitting a player in non-PvP area

### ISSUE THREAD

**Issue by Busted11290** [ShaneBeee/GriefPreventionFlags#66]
### Description
When a player throws a trident at another player inside a non-PvP area, the "Player vs. Player combat is restricted to designated areas." shows in chat.  The trident then poofs and the player loses the item.  One thing to note is that if it is in an Admin claimed area it gives a different message and the trident will fall to the ground.  If it is outside an Admin claim and anywhere pvp is not allowed, the trident will poof.

### Steps to Reproduce
- Give yourself a trident
- Find a player in a non-admin claimed & non-pvp area
- Throw trident at them
- Get the "Player vs. Player combat is restricted to designated areas." message
- Watch your trident vanish
- ???
- Cry

### Expected Behavior
I would expect it to deny the PvP damage and simply drop the trident so it can be picked back up.

### Errors / Screenshots
No console errors or screenshots.  I can get this on video if required.

### Server Information
* **Server version/platform:**     1.14.4 Paper-192
* **GriefPrevention Version:**        16.12.0
* **GriefPreventionFlags Version:**   5.6.3

### Additional Info
Nothing more to add about tridents.  Arrows seem to also do this but it is more random.

**Comment by ShaneBeee** [comment]
Good news and bad news!!

**Good news:**
I can prevent the removal of the trident I'm sure.

**Bad news:**
I'm going to assume the trident will just drop to the ground and the victim in the combat will be able to pick up your trident.

**Comment by Busted11290** [comment]
Well while that might could lead to problems between players on some servers, it is still better than total loss of the trident.

**Comment by ShaneBeee** [comment]
> Well while that might could lead to problems between players on some servers, it is still better than total loss of the trident.

I guess in retrospect, it's not going to be much different than if you threw a trident at a player and missed. The player would still be able to pick up the trident.

**Comment by ShaneBeee** [comment]
Fixed in 5.6.4
