### ISSUE TITLE
Apparent NoEnterPlayer bug

### ISSUE THREAD

**Issue by Weasel-Beans** [ShaneBeee/GriefPreventionFlags#69]
https://pastebin.com/eG2CrU7w

I noticed this bug in my console today. I encourage my players to use the NoEnterPlayer flag to keep specific users out of their claim if needed.

Edit: Here's a timings report for a list of plugins etc: 
https://timings.aikar.co/?id=6ca4e98d3e844188bb09829edef497b6

**Comment by ShaneBeee** [comment]
can you send your flags.yml

I have tried replicating this, and I cant seem to get it to error.

**Comment by Weasel-Beans** [comment]
Here you go: https://pastebin.com/7BL84k80

**Comment by ShaneBeee** [comment]
Hmm... looks about right. Ill keep testing and see if I can replicate the issue.

**Comment by ShaneBeee** [comment]
Can you try the latest release:
https://github.com/ShaneBeee/GriefPreventionFlags/releases/download/5.7.0/GriefPreventionFlags-5.7.0.jar

I did a big update to how the movement flags work, hopefully it solves some issues.

**Comment by Weasel-Beans** [comment]
Right, I did update that once I saw it on Spigot. I haven't seen the issue appear in the console, but I don't monitor it that closely. I suspect that may have solved it though.
