### ISSUE TITLE
NoMobSpawns or/and NoMonsterSpawns flags bug?

### ISSUE THREAD

**Issue by pinkpig3777** [ShaneBeee/GriefPreventionFlags#71]
For the last few months, my players have noticed that NoMobSpawns or/and NoMonsterSpawns flags have been set in claims where they never set those flags in.

Is there a way to prevent this or is this a bug? I can't seem to find anything in the config about it.

config.yml: https://pastebin.com/XtxrdWsc
/version: Paper version git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Thanks!

**Comment by ShaneBeee** [comment]
Flags won't auto set themselves.
Any chance you have set default flags, or world/server wide flags?

**Comment by pinkpig3777** [comment]
> Any chance you have set default flags, or world/server wide flags?
default flags from this plugin? Or from WorldGuard (& similar)? No worldguard flags or similar that would impact this as far as I know. As for GriefPreventionFlags, I don't think there are default flags..? Correct me if I'm wrong.

> also, can you send your flags.yml
flags.yml: https://pastebin.com/CqDnZMKz

**Comment by ShaneBeee** [comment]
From your config:
`# Plugin Version: 5.5.3`
Are you actually using GP Flags 5.5.3?

It almost seems like someone set a default flag which would add said flag to all claims.

**Comment by pinkpig3777** [comment]
> From your config:
> `# Plugin Version: 5.5.3`
> Are you actually using GP Flags 5.5.3?
> 
> It almost seems like someone set a default flag which would add said flag to all claims.

I just updated to the most recent version of the plugin a few hours ago (after experiencing this issue) just to make sure it was the most recent version. I'm not sure which version I was on before that, but I am at least now on 5.6.4.

Also, how does one set a default flag? I've not been an owner on this server for a few months so they could've changed something I'm not aware of.

**Comment by ShaneBeee** [comment]
> Also, how does one set a default flag? I've not been an owner on this server for a few months so they could've changed something I'm not aware of.

There is a command `/SetDefaultClaimFlag <flag here>`, I will need to do some testing, because I would assume this should show up in the flags.yml file somewhere.
