### ISSUE TITLE
NoVehicle flag is redundant, requesting AllowVehicle flag.

### ISSUE THREAD

**Issue by BongEatBong** [ShaneBeee/GriefPreventionFlags#73]
Since GriefPrevention's default setting is to not allow placing minecarts or boats in claimed areas, NoVehicle doesn't really have a use. That said, if a flag such as AllowVehicle had a use, it would be awesome. My server has an island spawn where I've built a dock. The problem is that GriefPrevention does not allow for boat placement, which is a bummer.

You mentioned on Discord that it may not be possible to do this, but to put it in the issue tracker for later review.

**Comment by ShaneBeee** [comment]
So looking thru GPs code, there is no way to "allow" boats whenever GP denies it.

I think the purpose for this flag was to disallow players placing vehicles in an instance when they were allowed to place them. I honestly can't remember the reason behind it when the requester requested the NoVehicle flag.
