### ISSUE TITLE
Flags from deleted claims stay in flags.yml file

### ISSUE THREAD

**Issue by arboriginal** [ShaneBeee/GriefPreventionFlags#74]
### Description
When you delete a claim, GPFlags/flags.yml keep flags of this deleted claim.

### Steps to Reproduce
1. Create a claim
2. Set a flag
3. Delete the claim
4. Look at GPFlags/flags.yml, the deleted claim ID still contain datas associated

### Expected Behavior
When a claim is deleted, remove datas for this to GPFlags/flags.yml.

### Errors / Screenshots
https://www.latlmes.com/world/gpflags-1

### Server Information
* **Server version/platform:** Paper-8 (API version 1.15-R0.1-SNAPSHOT)
* **GriefPrevention Version:** 16.12.0-d4d7ac4
* **GriefPreventionFlags Version:** 5.6.4

### Additional Info
it is not the spoon that bends, it is only yourself.

**Comment by ShaneBeee** [comment]
Hmmm.... I totally thought they did delete from the flags.yml, they're supposed to.
I will do some investigating and see what the issue is.

**Comment by arboriginal** [comment]
I though it was the case too, and I'm not sure but maybe we already had discussed about it last year (in the period I've PR this repo to situate in time) and maybe you already had fixed it in the past and a newer commit revert it.

I'm missing time now to make a PR, but I suppose you can easily do it by listening the GP event "deleteClaim" (I've verified it exists when I posted the issue but not sure of the name) if it's not yet implemented in GPFlags.

**Comment by ShaneBeee** [comment]
So, I totally thought they deleted before or something on a server restart. Seems that is not that case, but I did notice this

- create a claim or 2.
- add some flags to it. (Flags are now in the flags.yml file)
- abandon claims
- claims are still in the yaml file
- create a new claim, add a new flag to it
- old flags are removed.

So they are getting removed at some point. Ill have to work on something to remove the flags when a claim is deleted.

**Comment by arboriginal** [comment]
If old deleted datas dont stay forever, it's not a big deal, and maybe you could change the label from bug to improvement + defer to a low priority. When I saw that, I though they will never been deleted and was afraid the file will grow and grow...

**Comment by ShaneBeee** [comment]
Its definitely a bug still. I found the code, its supposed to remove them on server load, but for some reason its not saving the file, is what it looks like.

**Comment by ShaneBeee** [comment]
sooooo.... it was missing a save method.
So with this fix, the claim file will get updated when either a new flag is added or the server starts/restarts/gpflags reloads config.

I could make a listener for when a claim is abandoned and delete said flags, but at the end of the day it's not necessarily needed.

**Comment by ShaneBeee** [comment]
Fixed
