### ISSUE TITLE
Biome change not work with 1.15.1

### ISSUE THREAD

**Issue by andris155** [ShaneBeee/GriefPreventionFlags#76]
### Description

Biome change not work with 1.15.1

### Steps to Reproduce

/setclaimflag changebiome JUNGLE
Biome don't changed.

### Expected Behavior

Biome change work

### Server Information
* **Server version/platform:** This server is running Paper version git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
* **GriefPrevention Version:** GriefPrevention version 16.12.0-d4d7ac4
* **GriefPreventionFlags Version:** GriefPreventionFlags version 5.7.0

**Comment by ShaneBeee** [comment]
I figured this was going to happen.
1.15 has changed how biomes work. I will try to make a fix for this, but due to how biomes changed this might be a slight mess.

**Comment by ShaneBeee** [comment]
Okay, so good news and bad news.
**Good News:**
I was able to fix the biomes not setting. Rather simply I might add. The old method should have worked but changing one stupid little detail made it work.

**Bad News:**
Mojang went and screwed up how biomes work. Or Maybe its a Spigot bug, Im going to look into it more, but here is the issue, if you set the biome of A BLOCK in a chunk, it sets the biomes for ALL the blocks in a chunk... wtf?!?! OYYY this is frustrating. 

For the time being, I HIGHLY RECOMMEND not using this flag. 

I will do some testing and see if this is something Spigot can actually fix, and then hopefully if they do I can work on properly fixing this flag.

**Comment by andris155** [comment]
The PlotSquared solved it well biome change on 1.15.1. Look at the source code.

**Comment by ShaneBeee** [comment]
Doesn't plot squared use chunks though?!?!

GP claims can be any shape/size. After doing a crap ton of testing, even if I try to change a small 4x4 area, it still changes the biomes for the whole chunk.

**Comment by ShaneBeee** [comment]
Ok so this has been fixed and an update has been released.
Special note:
Part of this issue was due to a bug in Spigot, so you will need to update your Spigot jar as well.
If you are running Paper, please make sure to use the latest Paper build as well. (Paper#88 got this fix as well)
