### ISSUE TITLE
Flight Disabled message acting weird

### ISSUE THREAD

**Issue by DrakePork** [ShaneBeee/GriefPreventionFlags#77]
### Description
On any claims without a fly flag set, when you leave and enter the claim "Flight disabled" appears in chat. If a claim has a fly flag set, it doesnt say "Flight disabled" when entering the claim, but says it twice when leaving the claim.

### Steps to Reproduce
Create a claim and walk in and out of it.

### Expected Behavior
To not say flight disabled if a fly flag is not set, and to only say it once when a fly flag is set.

### Server Information
* **Server version/platform:**        Paper 1.15.1
* **GriefPrevention Version:**       16.12.0-d4d7ac4
* **GriefPreventionFlags Version:**   5.7.1

**Comment by ShaneBeee** [comment]
Dear lord these stupid flight flags are going to be the death of me ... swear to god.

Ok thanks for letting me know, Ill take a look at it soon.
