### ISSUE TITLE
Adminclaims has no "allow interaction" flag

### ISSUE THREAD

**Issue by xorinzor** [ShaneBeee/GriefPreventionFlags#8]
We use the AdminClaim to protect our spawn, but found out that players aren't allowed to interact with the villagers inside it.

Presumably this also affects levers, chests, etc inside the admin claim.

Is it possible to add a flag for allowing interaction in a claim?

**Comment by ShaneBeee** [comment]
Robo confirmed, /ContainerTrust does extend to villagers
`Yes. Villagers are containers since their trades can be exhausted.`

**Comment by xorinzor** [comment]
Yeah you're right, I forgot to update the ticket, but one of our staff members found that out too and applied the change. Thanks though!

**Comment by ShaneBeee** [comment]
> Yeah you're right, I forgot to update the ticket, but one of our staff members found that out too and applied the change. Thanks though!

You're very welcome :)
