### ISSUE TITLE
NoEnter flag can be bypassed using teleport in 1.15.1

### ISSUE THREAD

**Issue by ArtNRG** [ShaneBeee/GriefPreventionFlags#80]
### Description
NoEnter flag can be bypassed using teleport. 

### Steps to Reproduce
1. Place your /sethome location inside the other player claim
2. Add the NoEnter flag into that claim
3. You will be able to teleport there and unable to enter

### Expected Behavior
You are not able to neither walk inside the claim no teleport there.

### Server Information
git-Paper-35 (MC: 1.15.1)
GriefPrevention version 16.12.0-d4d7ac4
GriefPreventionFlags version 5.7.2

**Comment by ShaneBeee** [comment]
so the issue is, the essentials `/home` command does not call the teleport event... Im not exactly sure how to work around this.
