### ISSUE TITLE
Claim Fly Problem

### ISSUE THREAD

**Issue by coco0325** [ShaneBeee/GriefPreventionFlags#82]
### Description

If you stand in the outside of a claim, and adjust the claim size, you can fly in anywhere.

### Errors / Screenshots

No error.

### Server Information
* **Server version/platform:**        
Paper 1.14.4
* **GriefPrevention Version:**        
16.12.0
* **GriefPreventionFlags Version:**   
5.8.0

**Comment by ShaneBeee** [comment]
Can you provide more info?
Ex, what flags you had set in this claim?!?

**Comment by coco0325** [comment]
MemberFly
