### ISSUE TITLE
Animals despawn after setting flag NoMobSpawnsType iron_golem

### ISSUE THREAD

**Issue by dwesolowski** [ShaneBeee/GriefPreventionFlags#84]
### Description
After setting the flag /setclaimflag NoMobSpawnsType iron_golem my animals in my farms despawned shortly after. I removed the flag and re added animals and seems ok.

### Server Information
Paper 1.15.2 build 86
GriefPrevention Version: 16.12.0
GriefPreventionFlags Version: 5.8.2

**Comment by ShaneBeee** [comment]
Oh I think I see the issue, how embarrassing. I'll get this fixed up shortly!

**Comment by dwesolowski** [comment]
Will you be posting a update on spigot or should I compile?

**Comment by ShaneBeee** [comment]
Yes Ill post one shortly. I didn't want to post one last night due to I just posted one a few hours before that.
