### ISSUE TITLE
/unclaim Disabling fly for people in claim

### ISSUE THREAD

**Issue by BiGUNMAN** [ShaneBeee/GriefPreventionFlags#86]
### Description
When someone does /unclaim, everyone inside the claim including non-members have their fly toggled off. 

### Steps to Reproduce
Described above

### Expected Behavior
Players in fly should not lose their fly ability.

### Server Information
* **Server version/platform:** Paper 1.15.2
* **GriefPrevention Version:** 16.13.0
* **GriefPreventionFlags Version:** 5.8.3

### Additional Info
Described in this spigot post as well: https://www.spigotmc.org/threads/griefprevention-flags.314691/page-25#post-3692436

**Comment by BiGUNMAN** [comment]
Would you be able to release a new compiled release with this fix? @ShaneBeee

**Comment by ShaneBeee** [comment]
I probably should do that shouldn't I?
My bad, I must be brain fried I totally thought I did!
Ill try get it out in the next couple hours here.
