### ISSUE TITLE
CONSOLE

### ISSUE THREAD

**Issue by botany111** [ShaneBeee/GriefPreventionFlags#87]
Hide exit command

[Tue, 25. Feb 2020 11:23:09 UTC INFO] [GPFlags] Exit command: fly Pig0803 disable
[Tue, 25. Feb 2020 11:23:09 UTC INFO] CONSOLE issued server command: /fly Pig0803 disable

**Comment by ShaneBeee** [comment]
Care to elaborate?

This feature has been part of this plugin forever. Many users may rely on this feature. I can't just remove it because you want it removed.

**Comment by botany111** [comment]
I just want to hide the message
Sorry my english is not very good

**Comment by ShaneBeee** [comment]
I guess I could make the logs configurable. I don't want to straight up remove them.

**Comment by botany111** [comment]
How do I enable him?

**Comment by ShaneBeee** [comment]
open up the config, you'll see it there.
