### ISSUE TITLE
Flags disabled when teleport-ed from nether.

### ISSUE THREAD

**Issue by chacoby7** [ShaneBeee/GriefPreventionFlags#89]
### Description
When players teleport home from the nether, claim flags are not enabled.

### Steps to Reproduce
Create a claim, set claim flag ownermemberfly, go to the nether, teleport home using essentials /home command.

### Expected Behavior
When teleporting home from the nether into a claim I am greeted with a message "Flight enabled" however it is not enabled. This is fixed by simply walking out of the claim and back in or logging out and back in. I noticed its not just fly but other flags are not enabled either such as nofalldamage.

### Errors / Screenshots
No errors in console or in chat. I don't think screenshots are necessary. 

### Server Information
1.15.2 paper-120 java edition
GriefPrevention 16.13.0
GriefPrevention Flags 5.8.4

### Additional Info
EDIT: verion of essentialsx
EssentialsX 2.17.2.1

It appears this issue occurs when a player teleports between every world.

**Comment by ShaneBeee** [comment]
Ok, so after a ton of testing I couldn't replicate it.
Then I realized I had the permission `essentials.fly`
When I disabled that permission I noticed I could not fly, as you stated.

Long story short, I believe this is essentials overriding somehow and blocking this.
Im assuming they're doing a flight check when the player changes worlds.
Im not really sure theres much I can do here.
