### ISSUE TITLE
Request: Flag Permissions

### ISSUE THREAD

**Issue by lhdev** [ShaneBeee/GriefPreventionFlags#9]
I think it would be great to allow players to set flags if they have the proper permission to set that flag.
I have no idea what the implications are in the code to do something like this, but allowing players to set certain flags on their claims could be really nice.

An Example:
gpflags.setflag.entermessage

This would allow any player with that permission to set the EnterMessage Flag for their claim.

**Comment by lhdev** [comment]
Derp, I read through the perms and completely misread that one.
Sorry :)

**Comment by ShaneBeee** [comment]
No need to apologize, thats an easy one to miss
