### ISSUE TITLE
Flags break on start up of server.

### ISSUE THREAD

**Issue by VexiusNetworkUS** [ShaneBeee/GriefPreventionFlags#91]
Some of the flags don't work such as playertime and noenter. They seem to work sometimes and then they stop. version 5.8.2

**Comment by ShaneBeee** [comment]
I've tested many times and never had any issues. I'm going to need more info.

**Comment by ShaneBeee** [comment]
Closing due to extreme lack of information and lack of response. Also, I could not replicate such an issue.
