### ISSUE TITLE
No Enter Flag Bug

### ISSUE THREAD

**Issue by coco0325** [ShaneBeee/GriefPreventionFlags#92]
### Description
No enter flag allow player ride their boat in.

### Steps to Reproduce
https://cdn.discordapp.com/attachments/682783069308321809/696238364055175208/Minecraft_1.15.2_-__2020-04-05_12-22-41.mp4

### Server Information
* **Server version/platform:**        Paper 1.15.2
* **GriefPrevention Version:**        16.13.0
* **GriefPreventionFlags Version:**  5.8.5

**Comment by ShaneBeee** [comment]
I dont really think there is much I could do about this.

**Comment by coco0325** [comment]
Can you tell me why?

**Comment by ShaneBeee** [comment]
Im just not sure how to detect the movement in a boat, if its not already calling the player move event.

**Comment by coco0325** [comment]
Periodic checking player's location?
