### ISSUE TITLE
Flight not disabled after exit claim

### ISSUE THREAD

**Issue by TchicX** [ShaneBeee/GriefPreventionFlags#95]
### Description
I use the flag(s) OwnerMemberFly & OwnerFly (both added) to get flight as a member/owner within my own claim. I do get flight inside my own claim, but when I exit my claim I can still fly.

### Steps to Reproduce
1.Make a claim.
2. Set the default flag to either _OwnerMemberFly_ or _OwnerFly_.
3. Enter your claim (if already in go in and out).
4. Leave the claim.

### Expected Behavior
When I exit the claim my flight should be disabled.

### Server Information
* **Server version/platform:**        Paper version git-Paper-220 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
* **GriefPrevention Version:**        GriefPrevention version 16.13.0
* **GriefPreventionFlags Version:**   GriefPreventionFlags version 5.8.5

### Additional Info
I have tried removing my flight permission from essentialsX, but to no help.

**Comment by ShaneBeee** [comment]
Are you OP'd?

**Comment by TchicX** [comment]
> Are you OP'd?

No I am not OP.

**Comment by ShaneBeee** [comment]
I can not replicate this issue:
<img width="966" alt="Screen Shot 2020-04-27 at 1 41 49 PM" src="https://user-images.githubusercontent.com/20008482/80418882-f24aaa80-888c-11ea-9f50-e5dde3aaedc7.png">

**Comment by Ironic8b498** [comment]
got same issue, but only if players leave claim from below low level limit
