### ISSUE TITLE
Show disabled flags of subdivided claims

### ISSUE THREAD

**Issue by Folas1337** [ShaneBeee/GriefPreventionFlags#96]
### Description
An example:
- You have a mob spawner in a subdivision claim of the main claim
- You enable "noMonsterSpawns" in the main claim
- You disable "noMonsterSpawns" in the subdivided claim
If you now try and look up the flags for the subdivided claim ("/claimflags") you won't see that it's disabled in there.

Would be nice to have a "-noMonsterSpawns" in that case so you still know what flags are disabled or enabled where :)

Thanks in advance
~Folas1337

**Comment by ShaneBeee** [comment]
So I tested and it shows up for me:
<img width="966" alt="Screen Shot 2020-04-30 at 9 31 35 PM" src="https://user-images.githubusercontent.com/20008482/80782226-11b23380-8b2a-11ea-817b-fb80bbfad815.png">

**Comment by Folas1337** [comment]
In my test world it seems to work fine but in the main world it somehow isn't. Not entirely sure what's causing this but I'm assuming it's some plugin but I just can't figure out which one yet.

Will do more testing and report back.

**Comment by Folas1337** [comment]
It seems to be working now. Might have been a server restart, might have been the user not using it properly or an update of another plugin, I can't really tell right now but it seems to be fixed.

Closing the issue here.
