### ISSUE TITLE
flight not disabling after you leave Protected area

### ISSUE THREAD

**Issue by Ironic8b498** [ShaneBeee/GriefPreventionFlags#98]
### Description
Only if players leave claim from below, if they go under the Maximum depth, In grief prevention, in config set this, " MaximumDepth: 40"

### Steps to Reproduce
go below maximum depth and fly out of region

### Expected Behavior
flight not to engage below maximum depth

### Errors / Screenshots
video to help you understand if needed
https://www.dropbox.com/s/rc3mtg2wxxvk0yq/2020-05-11%2019-52-36.mp4?dl=0

### Server Information
* **Server version/platform:**         Debian 4.9.189-3+deb9u2
GriefPrevention Version: GriefPrevention version 16.13.0
GriefPreventionFlags Version: GriefPreventionFlags version 5.9.0

**Comment by Ironic8b498** [comment]
where can I download this fix?

**Comment by ShaneBeee** [comment]
I haven't posted anything yet.
